### ISSUE TITLE
Video orientation change in Andriod O

### ISSUE THREAD

**Issue by NitishAgrawal** [cornedor/react-native-video-player#94] opened 2018-06-06 14:13 UTC
The video is working well in iOS also in Android less then O But in API level 26 Android O it's orientation fix to landscape.

**Comment by petrogad** [comment] 2018-09-26 19:00
@NitishAgrawal - I believe this should fix your problem. 

https://github.com/cornedor/react-native-video-player/issues/101#issuecomment-424831921

Cheers

**Comment by TheRav3n** [comment] 2020-06-11 11:17
Closing as duplicate of #101

**Closed by TheRav3n** 2020-06-11 11:17 UTC
