### ISSUE TITLE
Android: crash due to backgroundColor

### ISSUE THREAD

**Issue by gsavvid** [cornedor/react-native-video-player#14] opened 2017-03-14 08:53 UTC
On my Android phone (7.1.1) I get the a crash `Error while updating property 'backgroundColor' of a View managed by: RCTVideo`. This doesn't happen on Genymotion with Android 5.0.0.

The problem is resolved if you remove `backgroundColor` from `styles.video`.

**Comment by cornedor** [comment] 2017-03-14 09:52
What is the color you are trying to set?

**Comment by gsavvid** [comment] 2017-03-14 10:06
I'm not trying to set any color. When I said `styles.video` I was referring to the style that is defined in the library (inside index.js, line 29).

**Comment by cornedor** [comment] 2017-03-16 08:58
Sorry, but I cannot reproduce this. Do you have the same issue when you run the example on your phone?

**Comment by cornedor** [comment] 2017-03-22 08:43
@gsavvid have you been able the solve this?

**Comment by gsavvid** [comment] 2017-03-22 13:31
@cornedor Yes, I solved it by commenting out the following line from `index.js` of `react-native-video-player`:

```
  video: {
    // backgroundColor: 'black',
  },
```

**Comment by cornedor** [comment] 2017-03-22 18:16
Thanks for the update, I'll close the issue for now since it works on my 5X with 7.1.1.

If someone else has the same issue I'll reopen it.

**Closed by cornedor** 2017-03-22 18:16 UTC
