### ISSUE TITLE
Any way to get current play through time?

### ISSUE THREAD

**Issue by theRedster** [cornedor/react-native-video-player#93] opened 2018-06-04 14:57 UTC
I wanted to implement a feature which shows a pop-up when the time in the video has reached a certain point, is there any way of doing this with react-native-video-player?

**Comment by TheRav3n** [comment] 2020-06-11 11:19
Closing as duplicate of #99 

There is currently no way, but there is a enhancement request open.

**Closed by TheRav3n** 2020-06-11 11:19 UTC
