### ISSUE TITLE
How to play only one video at a time? 

### ISSUE THREAD

**Issue by AkshayUk** [cornedor/react-native-video-player#130] opened 2020-10-09 07:09 UTC
Hi, I have multiple videos in a flatlist, how can i play only one video at a time? i.e.; when I play a new video in list, all other videos should be stopped. Right now, I can play any number of videos I want in the flatlist and all continue to play at them same time. Any help is appreciated, thanks in advance.

**Comment by TheRav3n** [comment] 2020-10-09 07:42
Hello  AkshayUk,

You will have to keep an array of `useRef()`, so `const myRef = useRef([])`.

Connect refs to the array by doing `ref={el => myRef.current[i] = el}`.

Then, programmatically call method `stop()` on all other players when `onPlayPress()` is fired on a specific player.

Closing as the issue is resolved.

**Closed by TheRav3n** 2020-10-09 07:42 UTC
Labels: question

**Comment by AkshayUk** [comment] 2020-10-09 09:39
Hi Thank you for the response. Also wanted to ask if there is a way to programmatically play the video? Right now we have to tap on the video to play it. I Even tried resume() , didn't seem to work.

**Comment by TheRav3n** [comment] 2020-10-09 10:13
`autoplay`

**Comment by AkshayUk** [comment] 2020-10-09 10:21
Yes, i did give autoplay a try. Unfortunately it seems to autoplay all the videos in list when set to true. That's why i was looking for an option to play only the specific video using the Ref.

**Comment by AkshayUk** [comment] 2020-10-09 12:55
I got it working by doing this 
`autoplay={true}
 paused={index === visibleIndex ? false : true}`
Thanks.

**Comment by TheRav3n** [comment] 2020-10-09 12:58
By the way, as a user, I would happily keep just one video per screen. I don't think it's a good idea to use a FlatList of videos in a mobile device.

**Comment by AkshayUk** [comment] 2020-10-09 13:03
The app i am currently working on is something similar to Instagram where you would get posts - either images/videos in your homescreen that you can scroll through. :D

**Comment by TheRav3n** [comment] 2020-10-09 13:05
Indeed you should use a wrapping component in the flatlist, such as a card and render videos only when they are about to go onscreen
