### ISSUE TITLE
At the end of the play, typeError.

### ISSUE THREAD

**Issue by laibinCN** [cornedor/react-native-video-player#84] opened 2018-03-23 10:43 UTC
Exapmle code,
```
<VideoPlayer
            endWithThumbnail
            thumbnail={{uri: this.state.thumbnailUrl}}
            video={{uri: this.state.videoUrl}}
            videoWidth={this.state.video.width}
            videoHeight={this.state.video.height}
            duration={this.state.video.duration/* I'm using a hls stream here, react-native-video
              can't figure out the length, so I pass it here from the vimeo config */}
            ref={r => this.player = r}
          />
```
at the end of the play
```
TypeError:null is not an object(evaluating '_this2.palyer.seek')
    this error is located at:
    in videoplayer(at index.js:35)
```

```
<VideoPlayer
            endWithThumbnail={false}
            thumbnail={{uri: this.state.thumbnailUrl}}
            video={{uri: this.state.videoUrl}}
            videoWidth={this.state.video.width}
            videoHeight={this.state.video.height}
            duration={this.state.video.duration/* I'm using a hls stream here, react-native-video
              can't figure out the length, so I pass it here from the vimeo config */}
            ref={r => this.player = r}
          />
```
If this is the case, Error will not occur.
Thank you！

**Comment by lossen** [comment] 2018-03-23 11:28
I have the same error.

**Comment by cornedor** [comment] 2018-03-27 08:39
@laibinCN you might have a typo, in `_this2.palyer.seek` is player written incorrectly. I can't find "palyer" the code on GitHub.

**Comment by jamsch** [comment] 2018-04-04 06:46
Occurs on iOS @ RN 0.55.0 for me. Android@0.54.2 seems fine. Gathering more info..

```javascript
 <VideoPlayer
      thumbnail={component.thumbnail ? { uri: component.thumbnail } : undefined}
      fullScreenOnLongPress
      video={{ uri: component.url }}
      videoWidth={400}
      videoHeight={225}
      loop={false}
      endWithThumbnail={Platform.OS === 'ios'}
    />
```

**Comment by alprtv** [comment] 2018-04-05 07:51
try 
`yarn add react-native-video-player@0.9.0`
it's worked for me

**Comment by melissayu** [comment] 2018-05-18 22:33
I get the same error with 0.9.1. Downgrading to 0.9.0 also fixed it for me.

**Comment by jeswinsimon** [comment] 2018-11-02 18:16
Duplicate of #79

**Comment by cornedor** [comment] 2018-11-07 15:52
This should now be fixed in the latest version.

**Closed by cornedor** 2018-11-07 15:52 UTC
Labels: bug
